# all: main.cpp
# 	clear
# 	g++ -g -std=c++11 -o main.out main.cpp Date.cpp Gregorian.cpp Julian.cpp
# 	./main.out
	
# all: datatest.cpp
# 	clear
# 	g++ -g -std=c++11 -o test.out datatest.cpp Date.cpp Gregorian.cpp Julian.cpp
# 	./test.out








# ------	With kattistime		-----

# all: main.cpp
# 	clear
# 	g++ -g -std=c++11 -o main.out main.cpp Date.cpp Gregorian.cpp Julian.cpp kattistime.cpp
# 	./main.out



# all: datatest.cpp
# 	clear
# 	g++ -g -std=c++11 -o test.out datatest.cpp Date.cpp Gregorian.cpp Julian.cpp kattistime.cpp
# 	./test.out








# # CALENDER test


all: main.cpp
	clear
	g++ -g -std=c++11 -o main.out mainTEST.cpp Date.cpp Gregorian.cpp Julian.cpp kattistime.cpp
	./main.out





